pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildName: "MyCppBuild"
  buildNumberFormat: $(rev:.r).$(Build.SourceVersionShort)

name: $(Build.DefinitionName)$(Rev:.r).$(Build.SourceVersion)
steps:
  - script: |
      sudo apt-get install libboost-all-dev
    displayName: Install dependencies
    

  - script: |
      g++ -std=c++11 -I/usr/include/boost/asio -I/usr/include/boost -o $(Build.ArtifactStagingDirectory)/$(buildName).$(buildNumberFormat).out main.cpp connection.cpp connection_manager.cpp mime_types.cpp reply.cpp request_handler.cpp request_parser.cpp server.cpp -lboost_system -lboost_thread -lpthread
    displayName: Compile the binaries
    
  - script: |
      echo $(name) > $(Build.ArtifactStagingDirectory)/readme.txt
    displayName: Generate readme.txt
    

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: drop